In [2]:
import matplotlib.pyplot as plt
import numpy as np

In [12]:
import sys
sys.path.append("..")

In [4]:
import importlib
from src.extract_candidate_features import extract_career_history_features
from schema.candidate_schema import CandidateSchema

In [ ]:
import json

importlib.reload(sys.modules['src.extract_candidate_features'])
importlib.reload(sys.modules['schema.candidate_schema'])
from src.extract_candidate_features import extract_career_history_features
from schema.candidate_schema import CandidateSchema

candidates = []

with open(
    r"C:\Users\Eternity\Dropbox\Projects\New folder\[PUB] India_runs_data_and_ai_challenge\[PUB] India_runs_data_and_ai_challenge\India_runs_data_and_ai_challenge\candidates.jsonl",
    "r",
    encoding="utf-8"
) as f:

    candidates = [
        CandidateSchema.model_validate(json.loads(line))
        for line in f
    ]

features = [
    extract_career_history_features(candidate)
    for candidate in candidates
]

# print(features[0])

gap_months = []

# startup_counts = []
startup_months = []
startup_ratios = []

product_months = []
product_ratios = []

service_months = []
service_ratios = []

unknown_company_months = []
unknown_company_ratios = []

tech_title_ratios = []
ai_ml_title_ratios = []

for candidate in candidates:
    print(candidate.career_history.duration_months)

for career in features:

    # startup_counts.append(
    #     career["start_up_based_experience"]
    # )

    gap_months.append(
        career["career_gap_months"]
    )

    startup_months.append(
        career["startup_based_experience_months"]
    )

    startup_ratios.append(
        career["startup_based_experience_ratio"]
    )

    product_months.append(
        career["product_based_experience_months"]
    )

    product_ratios.append(
        career["product_based_experience_ratio"]
    )

    service_months.append(
        career["service_based_experience_months"]
    )

    service_ratios.append(
        career["service_based_experience_ratio"]
    )

    unknown_company_months.append(
        career["unknown_company_experience_months"]
    )

    unknown_company_ratios.append(
        career["unknown_company_experience_ratio"]
    )

    tech_title_ratios.append(
        career["tech_title_ratio"]
    )

    ai_ml_title_ratios.append(
        career["ai_ml_title_ratio"]
    )



# Startup role count

# print("Startup Count")
# print(np.percentile(startup_counts, [25, 50, 65, 70, 75, 90, 95]))

print("\nCareer Gap Months")
print(np.percentile(gap_months, [10, 25, 50, 65, 70, 75, 90, 95]))

print("\nStartup Months")
print(np.percentile(startup_months, [10, 25, 50, 65, 70, 75, 90, 95]))

print("\nStartup Ratio")
print(np.percentile(startup_ratios, [10, 25, 50, 65, 70, 75, 90, 95]))

print("\nProduct Months")
print(np.percentile(product_months, [10, 25, 50, 65, 70, 75, 90, 95]))

print("\nProduct Ratio")
print(np.percentile(product_ratios, [10, 25, 50, 65, 70, 75, 90, 95]))

print("\nService Months")
print(np.percentile(service_months, [10, 25, 50, 65, 70, 75, 90, 95]))

print("\nService Ratio")
print(np.percentile(service_ratios, [10, 25, 50, 65, 70, 75, 90, 95]))

print("\nUnknown Company Months")
print(np.percentile(unknown_company_months, [10, 25, 50, 65, 70, 75, 90, 95]))

print("\nUnknown Company Ratio")
print(np.percentile(unknown_company_ratios, [10, 25, 50, 65, 70, 75, 90, 95]))

print("\nTech Title Ratio")
print(np.percentile(tech_title_ratios, [10, 25, 50, 65, 70, 75, 90, 95]))

print("\nAI/ML Title Ratio")
print(np.percentile(ai_ml_title_ratios, [10, 25, 50, 65, 70, 75, 90, 95]))



Career Gap Months
[0. 0. 0. 0. 0. 0. 2. 2.]

Startup Months
[ 0.  0.  0. 13. 18. 25. 46. 56.]

Startup Ratio
[0.         0.         0.         0.11764706 0.19090909 0.25714286
 0.50980392 0.71000725]

Product Months
[ 0.  0.  0.  0.  0.  0. 26. 43.]

Product Ratio
[0.         0.         0.         0.         0.         0.
 0.4        0.72840388]

Service Months
[ 0.  0. 20. 33. 38. 43. 65. 80.]

Service Ratio
[0.         0.         0.23684211 0.3974359  0.45679012 0.52298851
 0.89655172 1.        ]

Unknown Company Months
[  0.  16.  45.  67.  75.  84. 119. 137.]

Unknown Company Ratio
[0.         0.30107527 0.66475631 0.85227273 1.         1.
 1.         1.        ]

Tech Title Ratio
[0.         0.         0.25633013 0.625      1.         1.
 1.         1.        ]

AI/ML Title Ratio
[0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
importlib.reload(sys.modules['utils.skills'])
from utils.skills.skill_names import SKILL_TAXONOMY

counts = []
max_durations = []
avg_durations = []
endorsements = []

for feature in features:

    skill_groups = feature["skill_features"]

    total_count = sum(
        s["count"]
        for s in skill_groups.values()
    )

    max_duration = max(
        (s["max_duration"] for s in skill_groups.values()),
        default=0
    )

    durations = [
        s["avg_duration"]
        for s in skill_groups.values()
        if s["count"] > 0
    ]

    avg_duration = (
        sum(durations) / len(durations)
        if durations else 0
    )

    total_endorsements = sum(
        s["endorsements"]
        for s in skill_groups.values()
    )

    counts.append(total_count)
    max_durations.append(max_duration)
    avg_durations.append(avg_duration)
    endorsements.append(total_endorsements)


print("\nSkill Count")
print(np.percentile(counts, [10,25,50,65,70,75,90,95]))

print("\nSkill Max Duration")
print(np.percentile(max_durations, [10,25,50,65,70,75,90,95]))

print("\nSkill Avg Duration")
print(np.percentile(avg_durations, [10,25,50,65,70,75,90,95]))

print("\nSkill Endorsements")
print(np.percentile(endorsements, [10,25,50,65,70,75,90,95]))


for group in SKILL_TAXONOMY:

    counts = [
        f["skill_features"][group]["count"]
        for f in features
    ]

    print(group)
    print(np.percentile(counts, [50,75,90,95]))

KeyError: 'skill_features'

In [ ]:
importlib.reload(sys.modules['src.extract_candidate_features'])
from src.extract_candidate_features import extract_redrob_signals

importlib.reload(sys.modules['utils.redrob_signals'])
from utils.redrob_signals.skill_assessment_taxonomy import SKILL_ASSESSMENT_TAXONOMY

view_rates = []
save_rates = []
recruiter_interest_scores = []
recruiters_response_rate = []
avg_response_times = []

connection_counts = []
endorsements_received = []

github_activity_scores = []

interview_completion_rates = []
offer_acceptance_rates = []

assignment_score = []



jd_features = {'preferred_locations': ['Pune', 'Noida'], 'additional_locations': ['Hyderabad', 'Mumbai', 'Delhi NCR'], 'relocation_preferred': True, 'employment_type': ['Full-time'],'work_mode': ['Hybrid'], 'experience_required': {'min': 5, 'max': 9}, 'must_have_skills': ['Production experience with embeddings-based retrieval systems', 'Production experience with vector databases', 'Python', 'Ranking system evaluation design', 'NDCG', 'MRR', 'MAP', 'A/B testing', 'Modern Machine Learning systems', 'LLMs', 'End-to-end Ranking Systems', 'End-to-end Search Systems', 'End-to-end Recommendation Systems'], 'preferred_skills': ['LLM fine-tuning', 'Learning-to-rank models', 'HR Tech', 'Recruiting Tech', 'Marketplace products', 'Distributed Systems', 'Large-scale inference optimization', 'Open-source contributions in AI/ML'], 'role_focus': ['Intelligencelayer development', 'Ranking system development', 'Retrieval system development', 'Matching system development', 'Candidate-Job Description matching', 'AI architecture'], 'education_requirements': [], 'company_type_preferences': ['Product company'], 'negative_signals': ['Pure research background without production deployment', 'AI experience primarily from recent LangChain/OpenAI projects without pre-LLM ML production experience', 'No production code written in last 18 months due to architecture/tech lead roles', 'Frequent job switching (every 1.5 years)', 'Title-chasing', 'Over-reliance on frameworks (lack of systems thinking)', 'Exclusive consulting firm background(e.g., TCS, Infosys)', 'Primary expertise in Computer Vision, Speech, or Robotics without significant NLP/IR exposure', 'Work entirely on closed-source proprietary systems for 5+ years without external validation'], 'notice_period': 30, 'salary_range': {'min': None, 'max': None}}



features_signals = [
    extract_redrob_signals(candidate, jd_features)
    for candidate in candidates
]

for feature in features_signals:

    view_rates.append(feature["view_rate"])
    save_rates.append(feature["save_rate"])
    recruiter_interest_scores.append(
        feature["recruiter_interest"]
    )
    recruiters_response_rate.append(
        feature["recruiter_response_rate"]
    )
    avg_response_times.append(
        feature["avg_response_time_hours"]
    )
    connection_counts.append(
        feature["connection_count"]
    )
    endorsements_received.append(
        feature["endorsements_received"]
    )

    github_activity_scores.append(
        feature["github_activity_score"]
    )

    interview_completion_rates.append(
        feature["interview_completion_rate"]
    )

    offer_acceptance_rates.append(
        feature["offer_acceptance_rate"]
    )



print("\n Skill Assessment Scores taken by candidates")
has_assessment = 0

for candidate in candidates:
    if candidate.redrob_signals.skill_assessment_scores:
        has_assessment += 1

print(has_assessment)
print(has_assessment / len(candidates))


print("\nSkill Assessment Scores Percentiles")
for group in SKILL_ASSESSMENT_TAXONOMY:

    counts = [
        f["assessment_features"][group]["avg_score"]
        for f in features_signals
    ]

    max_score = [
        f["assessment_features"][group]["max_score"]
        for f in features_signals
    ]

    print(group)
    print(np.percentile(counts, [10,25,50,65,70,75,90,95]))
    print(np.percentile(max_score, [10,25,50,65,70,75,90,95]))


print("\nView Rate")
print(np.percentile(view_rates, [10,25,50,65,70,75,90,95]))

print("\nSave Rate")
print(np.percentile(save_rates, [10,25,50,65,70,75,90,95]))

print("\nRecruiter Interest Score")
print(np.percentile(recruiter_interest_scores, [10,25,50,65,70,75,90,95]))

print("\nRecruiter Response Rate")
print(np.percentile(recruiters_response_rate, [10,25,50,65,70,75,90,95]))

print("\nAverage Response Time")
print(np.percentile(avg_response_times, [10,25,50,65,70,75,90,95]))



print("\nConnection Count")
print(np.percentile(connection_counts, [10,25,50,65,70,75,90,95]))

print("\nEndorsements Received")
print(np.percentile(endorsements_received, [10,25,50,65,70,75,90,95]))

print("\nGithub Activity Score")
print(np.percentile(github_activity_scores, [10,25,50,65,70,75,90,95]))

print("\nInterview Completion Rate")
print(np.percentile(interview_completion_rates, [10,25,50,65,70,75,90,95]))

print("\nOffer Acceptance Rate")
print(np.percentile(offer_acceptance_rates, [10,25,50,65,70,75,90,95]))


 Skill Assessment Scores taken by candidates
24244
0.24244

Skill Assessment Scores Percentiles
retrieval
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
vector_db
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
search_ranking
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
llm
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
fine_tuning
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
nlp
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
ml
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
mlops
[ 0.   0.   0.   0.   0.   0.   0.  27.9]
[ 0.   0.   0.   0.   0.   0.   0.  27.9]
computer_vision
[ 0.   0.   0.   0.   0.   0.   0.  37.9]
[ 0.  0.  0.  0.  0.  0.  0. 38.]
speech
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]

View Rate
[0.08080808 0.20987654 0.42528736 0.60968656 0.71186441 0.85416667
 2.1875     4.41322464]

Save Rate
[0.02083333 0.07142857 0.15492958 0.22222222 0.26086957 0.31578947
 0.8        1.66666667]

Recruiter Interest Score
[ 4.6  7.5

In [10]:
import numpy as np

from utils.load_candidates import load_candidates




def analyze_job_duration(candidates):

    durations = []

    for candidate in candidates:
        for role in candidate.career_history:
            durations.append(role.duration_months)

    durations = np.array(durations)

    print("Min:", durations.min())
    print("Mean:", durations.mean())
    print("Median:", np.median(durations))

    print("25% :", np.percentile(durations, 25))
    print("50% :", np.percentile(durations, 50))
    print("75% :", np.percentile(durations, 75))
    print("90% :", np.percentile(durations, 90))
    print("95% :", np.percentile(durations, 95))

candidates = load_candidates(r"C:\Users\Eternity\Dropbox\Projects\New folder\[PUB] India_runs_data_and_ai_challenge\[PUB] India_runs_data_and_ai_challenge\India_runs_data_and_ai_challenge\candidates.jsonl")

analyze_job_duration(candidates)

Min: 6
Mean: 28.23622868298403
Median: 27.0
25% : 18.0
50% : 27.0
75% : 38.0
90% : 46.0
95% : 50.0


In [13]:
import json
import numpy as np

disqualifier_features = np.load(
    "disqualifier_features.npy",
    allow_pickle=True
).item()

for key in [
    "research_similarity",
    "architecture_similarity",
    "langchain_similarity",
    "cv_similarity",
    "nlp_ir_similarity",
]:
    vals = [v[key] for v in disqualifier_features.values()]
    print(key)
    print("Min :", np.min(vals))
    print("P5  :", np.percentile(vals, 5))
    print("P95 :", np.percentile(vals, 95))
    print("Max :", np.max(vals))

FileNotFoundError: [Errno 2] No such file or directory: 'disqualifier_features.npy'